# Bilingual disease knowledge for the 38 PlantVillage classes the model predicts.
# Each entry: short description + first action, in English and Hindi.
# NOTE: This model does NOT cover paddy (rice) or arhar/tur. See README caveat.

DISEASE_INFO = {
    "Apple___Apple_scab": {
        "crop": {"en": "Apple", "hi": "सेब"},
        "disease": {"en": "Apple scab", "hi": "सेब स्कैब"},
        "desc": {"en": "Fungal disease causing dark, scabby lesions on leaves and fruit.",
                 "hi": "फफूंद रोग—पत्तियों और फल पर काले, खुरदरे धब्बे।"},
        "action": {"en": "Remove fallen leaves; apply a recommended fungicide at bud break.",
                   "hi": "गिरी पत्तियाँ हटाएँ; कली फूटने पर अनुशंसित फफूंदनाशक डालें।"},
    },
    "Apple___Black_rot": {
        "crop": {"en": "Apple", "hi": "सेब"},
        "disease": {"en": "Black rot", "hi": "ब्लैक रॉट"},
        "desc": {"en": "Fungus causing black rotten spots on fruit, leaves and bark.",
                 "hi": "फफूंद—फल, पत्ती व छाल पर काले सड़े धब्बे।"},
        "action": {"en": "Prune out cankers; remove mummified fruit; apply fungicide.",
                   "hi": "रोगग्रस्त टहनी काटें; सूखे फल हटाएँ; फफूंदनाशक डालें।"},
    },
    "Apple___Cedar_apple_rust": {
        "crop": {"en": "Apple", "hi": "सेब"},
        "disease": {"en": "Cedar apple rust", "hi": "सीडर एप्पल रस्ट"},
        "desc": {"en": "Fungus making yellow-orange spots; needs nearby cedar trees.",
                 "hi": "फफूंद—पीले-नारंगी धब्बे; पास के सीडर पेड़ से फैलता है।"},
        "action": {"en": "Remove nearby junipers if possible; apply fungicide early season.",
                   "hi": "पास के जुनिपर हटाएँ; मौसम की शुरुआत में फफूंदनाशक डालें।"},
    },
    "Apple___healthy": {
        "crop": {"en": "Apple", "hi": "सेब"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected. Plant looks healthy.",
                 "hi": "कोई रोग नहीं मिला। पौधा स्वस्थ दिख रहा है।"},
        "action": {"en": "Keep monitoring; maintain good spacing and irrigation.",
                   "hi": "निगरानी रखें; उचित दूरी व सिंचाई बनाए रखें।"},
    },
    "Blueberry___healthy": {
        "crop": {"en": "Blueberry", "hi": "ब्लूबेरी"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected. Plant looks healthy.",
                 "hi": "कोई रोग नहीं मिला। पौधा स्वस्थ दिख रहा है।"},
        "action": {"en": "Keep monitoring routine care.",
                   "hi": "सामान्य देखभाल जारी रखें।"},
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "crop": {"en": "Cherry", "hi": "चेरी"},
        "disease": {"en": "Powdery mildew", "hi": "चूर्णिल आसिता"},
        "desc": {"en": "White powdery fungal growth on leaves and shoots.",
                 "hi": "पत्तियों व टहनियों पर सफेद चूर्ण जैसी फफूंद।"},
        "action": {"en": "Improve air flow; apply sulfur or a recommended fungicide.",
                   "hi": "हवा का बहाव बढ़ाएँ; सल्फर/अनुशंसित फफूंदनाशक डालें।"},
    },
    "Cherry_(including_sour)___healthy": {
        "crop": {"en": "Cherry", "hi": "चेरी"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "crop": {"en": "Maize", "hi": "मक्का"},
        "disease": {"en": "Gray leaf spot", "hi": "ग्रे लीफ स्पॉट"},
        "desc": {"en": "Rectangular gray lesions on leaves; cuts photosynthesis.",
                 "hi": "पत्तियों पर आयताकार धूसर धब्बे; प्रकाश-संश्लेषण घटाता है।"},
        "action": {"en": "Rotate crops; use resistant hybrids; fungicide if severe.",
                   "hi": "फसल चक्र अपनाएँ; रोग-रोधी संकर बीज; गंभीर हो तो फफूंदनाशक।"},
    },
    "Corn_(maize)___Common_rust_": {
        "crop": {"en": "Maize", "hi": "मक्का"},
        "disease": {"en": "Common rust", "hi": "कॉमन रस्ट"},
        "desc": {"en": "Reddish-brown pustules on both leaf surfaces.",
                 "hi": "पत्ती की दोनों सतहों पर लाल-भूरे फफोले।"},
        "action": {"en": "Use resistant hybrids; fungicide if it spreads fast.",
                   "hi": "रोग-रोधी संकर बीज; तेज़ फैले तो फफूंदनाशक।"},
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "crop": {"en": "Maize", "hi": "मक्का"},
        "disease": {"en": "Northern leaf blight", "hi": "नॉर्दर्न लीफ ब्लाइट"},
        "desc": {"en": "Cigar-shaped gray-green lesions; can cause big yield loss.",
                 "hi": "सिगार-आकार के धूसर-हरे धब्बे; पैदावार घटा सकते हैं।"},
        "action": {"en": "Resistant hybrids + crop rotation; fungicide at early signs.",
                   "hi": "रोग-रोधी बीज + फसल चक्र; शुरुआती लक्षण पर फफूंदनाशक।"},
    },
    "Corn_(maize)___healthy": {
        "crop": {"en": "Maize", "hi": "मक्का"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring; scout weekly after rain.",
                   "hi": "निगरानी रखें; बारिश के बाद साप्ताहिक जाँच।"},
    },
    "Grape___Black_rot": {
        "crop": {"en": "Grape", "hi": "अंगूर"},
        "disease": {"en": "Black rot", "hi": "ब्लैक रॉट"},
        "desc": {"en": "Black spots on leaves and fruit; berries shrivel.",
                 "hi": "पत्ती व फल पर काले धब्बे; दाने सिकुड़ते हैं।"},
        "action": {"en": "Remove mummies; apply fungicide from bud break.",
                   "hi": "सूखे दाने हटाएँ; कली फूटने से फफूंदनाशक डालें।"},
    },
    "Grape___Esca_(Black_Measles)": {
        "crop": {"en": "Grape", "hi": "अंगूर"},
        "disease": {"en": "Esca (black measles)", "hi": "एस्का"},
        "desc": {"en": "Dark streaks in wood; spots on leaves and berries.",
                 "hi": "लकड़ी में काली धारियाँ; पत्ती-दाने पर धब्बे।"},
        "action": {"en": "Prune affected wood; avoid vine stress; no full cure.",
                   "hi": "रोगग्रस्त लकड़ी काटें; तनाव से बचाएँ; पूरा इलाज नहीं।"},
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "crop": {"en": "Grape", "hi": "अंगूर"},
        "disease": {"en": "Leaf blight", "hi": "लीफ ब्लाइट"},
        "desc": {"en": "Irregular necrotic spots that merge on leaves.",
                 "hi": "पत्तियों पर अनियमित मृत धब्बे जो मिल जाते हैं।"},
        "action": {"en": "Improve airflow; apply fungicide; remove debris.",
                   "hi": "हवा बढ़ाएँ; फफूंदनाशक डालें; कचरा हटाएँ।"},
    },
    "Grape___healthy": {
        "crop": {"en": "Grape", "hi": "अंगूर"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "crop": {"en": "Orange", "hi": "संतरा"},
        "disease": {"en": "Citrus greening (HLB)", "hi": "सिट्रस ग्रीनिंग"},
        "desc": {"en": "Bacterial disease spread by psyllids; yellow shoots, bad fruit.",
                 "hi": "सिला कीट से फैलने वाला जीवाणु रोग; पीली टहनी, खराब फल।"},
        "action": {"en": "Remove infected trees; control psyllids; no cure.",
                   "hi": "रोगग्रस्त पेड़ हटाएँ; सिला कीट रोकें; इलाज नहीं।"},
    },
    "Peach___Bacterial_spot": {
        "crop": {"en": "Peach", "hi": "आड़ू"},
        "disease": {"en": "Bacterial spot", "hi": "बैक्टीरियल स्पॉट"},
        "desc": {"en": "Water-soaked spots on leaves and fruit.",
                 "hi": "पत्ती-फल पर पानी-भरे धब्बे।"},
        "action": {"en": "Use resistant varieties; copper sprays; avoid overhead water.",
                   "hi": "रोग-रोधी किस्में; कॉपर स्प्रे; ऊपर से सिंचाई न करें।"},
    },
    "Peach___healthy": {
        "crop": {"en": "Peach", "hi": "आड़ू"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Pepper,_bell___Bacterial_spot": {
        "crop": {"en": "Bell pepper", "hi": "शिमला मिर्च"},
        "disease": {"en": "Bacterial spot", "hi": "बैक्टीरियल स्पॉट"},
        "desc": {"en": "Dark water-soaked spots on leaves and fruit.",
                 "hi": "पत्ती-फल पर गहरे पानी-भरे धब्बे।"},
        "action": {"en": "Use clean seed; copper sprays; rotate crops.",
                   "hi": "स्वच्छ बीज; कॉपर स्प्रे; फसल चक्र अपनाएँ।"},
    },
    "Pepper,_bell___healthy": {
        "crop": {"en": "Bell pepper", "hi": "शिमला मिर्च"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Potato___Early_blight": {
        "crop": {"en": "Potato", "hi": "आलू"},
        "disease": {"en": "Early blight", "hi": "अगेती झुलसा"},
        "desc": {"en": "Concentric ring spots on leaves; reduces tuber yield.",
                 "hi": "पत्तियों पर छल्लेदार धब्बे; कंद पैदावार घटती है।"},
        "action": {"en": "Rotate crops; remove infected leaves; apply fungicide.",
                   "hi": "फसल चक्र; रोगग्रस्त पत्ती हटाएँ; फफूंदनाशक डालें।"},
    },
    "Potato___Late_blight": {
        "crop": {"en": "Potato", "hi": "आलू"},
        "disease": {"en": "Late blight", "hi": "पछेती झुलसा"},
        "desc": {"en": "Water-soaked lesions; spreads fast, can destroy the crop.",
                 "hi": "पानी-भरे धब्बे; तेज़ फैलता है, पूरी फसल बर्बाद कर सकता है।"},
        "action": {"en": "Act fast: remove infected plants; apply fungicide immediately.",
                   "hi": "तुरंत कदम: रोगग्रस्त पौधे हटाएँ; तुरंत फफूंदनाशक डालें।"},
    },
    "Potato___healthy": {
        "crop": {"en": "Potato", "hi": "आलू"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring; scout after wet weather.",
                   "hi": "निगरानी रखें; नमी वाले मौसम बाद जाँचें।"},
    },
    "Raspberry___healthy": {
        "crop": {"en": "Raspberry", "hi": "रसभरी"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Soybean___healthy": {
        "crop": {"en": "Soybean", "hi": "सोयाबीन"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Squash___Powdery_mildew": {
        "crop": {"en": "Squash", "hi": "कद्दू वर्ग"},
        "disease": {"en": "Powdery mildew", "hi": "चूर्णिल आसिता"},
        "desc": {"en": "White powdery growth on leaves and stems.",
                 "hi": "पत्ती-तने पर सफेद चूर्ण जैसी वृद्धि।"},
        "action": {"en": "Improve airflow; apply sulfur/neem or fungicide.",
                   "hi": "हवा बढ़ाएँ; सल्फर/नीम या फफूंदनाशक डालें।"},
    },
    "Strawberry___Leaf_scorch": {
        "crop": {"en": "Strawberry", "hi": "स्ट्रॉबेरी"},
        "disease": {"en": "Leaf scorch", "hi": "लीफ स्कॉर्च"},
        "desc": {"en": "Dark purple spots that merge and dry the leaf.",
                 "hi": "गहरे बैंगनी धब्बे जो मिलकर पत्ती सुखाते हैं।"},
        "action": {"en": "Remove old leaves; improve airflow; fungicide if needed.",
                   "hi": "पुरानी पत्तियाँ हटाएँ; हवा बढ़ाएँ; ज़रूरत हो तो फफूंदनाशक।"},
    },
    "Strawberry___healthy": {
        "crop": {"en": "Strawberry", "hi": "स्ट्रॉबेरी"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring.", "hi": "निगरानी रखें।"},
    },
    "Tomato___Bacterial_spot": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Bacterial spot", "hi": "बैक्टीरियल स्पॉट"},
        "desc": {"en": "Small water-soaked spots on leaves and fruit.",
                 "hi": "पत्ती-फल पर छोटे पानी-भरे धब्बे।"},
        "action": {"en": "Use clean seed; copper sprays; avoid overhead water.",
                   "hi": "स्वच्छ बीज; कॉपर स्प्रे; ऊपर से सिंचाई न करें।"},
    },
    "Tomato___Early_blight": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Early blight", "hi": "अगेती झुलसा"},
        "desc": {"en": "Concentric ring lesions; causes leaf drop and yield loss.",
                 "hi": "छल्लेदार धब्बे; पत्ती गिरना व पैदावार हानि।"},
        "action": {"en": "Remove lower infected leaves; mulch; apply fungicide.",
                   "hi": "नीचे की रोगग्रस्त पत्तियाँ हटाएँ; मल्च; फफूंदनाशक डालें।"},
    },
    "Tomato___Late_blight": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Late blight", "hi": "पछेती झुलसा"},
        "desc": {"en": "Large water-soaked lesions; plant collapses fast.",
                 "hi": "बड़े पानी-भरे धब्बे; पौधा जल्दी सूखता है।"},
        "action": {"en": "Act fast: remove infected plants; fungicide immediately.",
                   "hi": "तुरंत कदम: रोगग्रस्त पौधे हटाएँ; तुरंत फफूंदनाशक।"},
    },
    "Tomato___Leaf_Mold": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Leaf mold", "hi": "लीफ मोल्ड"},
        "desc": {"en": "Yellow spots on top, olive mold underneath leaves.",
                 "hi": "ऊपर पीले धब्बे, नीचे जैतूनी फफूंद।"},
        "action": {"en": "Lower humidity; improve airflow; apply fungicide.",
                   "hi": "नमी घटाएँ; हवा बढ़ाएँ; फफूंदनाशक डालें।"},
    },
    "Tomato___Septoria_leaf_spot": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Septoria leaf spot", "hi": "सेप्टोरिया लीफ स्पॉट"},
        "desc": {"en": "Small circular spots with gray centers; early leaf drop.",
                 "hi": "धूसर केंद्र वाले छोटे गोल धब्बे; जल्दी पत्ती गिरना।"},
        "action": {"en": "Remove infected leaves; avoid wetting foliage; fungicide.",
                   "hi": "रोगग्रस्त पत्ती हटाएँ; पत्ती गीली न करें; फफूंदनाशक।"},
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Spider mites", "hi": "मकड़ी माइट"},
        "desc": {"en": "Tiny mites cause stippling and bronzing of leaves.",
                 "hi": "छोटे माइट—पत्तियों पर चित्ती व कांस्य रंग।"},
        "action": {"en": "Spray water; use neem oil or miticide; remove dust.",
                   "hi": "पानी छिड़कें; नीम तेल/माइटनाशक; धूल हटाएँ।"},
    },
    "Tomato___Target_Spot": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Target spot", "hi": "टारगेट स्पॉट"},
        "desc": {"en": "Dark concentric lesions on leaves, stems and fruit.",
                 "hi": "पत्ती-तना-फल पर गहरे छल्लेदार धब्बे।"},
        "action": {"en": "Remove debris; improve airflow; apply fungicide.",
                   "hi": "कचरा हटाएँ; हवा बढ़ाएँ; फफूंदनाशक डालें।"},
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Yellow leaf curl virus", "hi": "पीला पत्ती मोड़ वायरस"},
        "desc": {"en": "Whitefly-spread virus; yellowing, curling, stunting.",
                 "hi": "सफेद मक्खी से फैला वायरस; पीलापन, मुड़ना, बौनापन।"},
        "action": {"en": "Control whiteflies; remove infected plants; use resistant seed.",
                   "hi": "सफेद मक्खी रोकें; रोगग्रस्त पौधे हटाएँ; रोग-रोधी बीज।"},
    },
    "Tomato___Tomato_mosaic_virus": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Mosaic virus", "hi": "मोज़ेक वायरस"},
        "desc": {"en": "Mottling and leaf distortion; smaller fruit.",
                 "hi": "चित्तीदार व मुड़ी पत्तियाँ; छोटे फल।"},
        "action": {"en": "Remove infected plants; wash hands/tools; resistant seed.",
                   "hi": "रोगग्रस्त पौधे हटाएँ; हाथ/औज़ार धोएँ; रोग-रोधी बीज।"},
    },
    "Tomato___healthy": {
        "crop": {"en": "Tomato", "hi": "टमाटर"},
        "disease": {"en": "Healthy", "hi": "स्वस्थ"},
        "desc": {"en": "No disease detected.", "hi": "कोई रोग नहीं मिला।"},
        "action": {"en": "Keep monitoring; scout weekly.",
                   "hi": "निगरानी रखें; साप्ताहिक जाँच।"},
    },
}

# Ordered class list — MUST match the model's output order exactly.
CLASS_NAMES = [
    "Apple___Apple_scab", "Apple___Black_rot", "Apple___Cedar_apple_rust", "Apple___healthy",
    "Blueberry___healthy", "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy", "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_", "Corn_(maize)___Northern_Leaf_Blight", "Corn_(maize)___healthy",
    "Grape___Black_rot", "Grape___Esca_(Black_Measles)", "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy", "Orange___Haunglongbing_(Citrus_greening)", "Peach___Bacterial_spot",
    "Peach___healthy", "Pepper,_bell___Bacterial_spot", "Pepper,_bell___healthy",
    "Potato___Early_blight", "Potato___Late_blight", "Potato___healthy",
    "Raspberry___healthy", "Soybean___healthy", "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch", "Strawberry___healthy", "Tomato___Bacterial_spot",
    "Tomato___Early_blight", "Tomato___Late_blight", "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot", "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot", "Tomato___Tomato_Yellow_Leaf_Curl_Virus", "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]
